import { rankTrails, TRAIL_CATALOG, validateRequest, type WeatherInput } from "../../../../lib/recommendations";
import { saveRecommendations } from "../../../../lib/recommendation-store";

async function getWeather(date:string){
 if(process.env.TRAILSENSE_DISABLE_WEATHER==="1")throw new Error("Weather provider disabled");
 const params=new URLSearchParams({latitude:TRAIL_CATALOG.map(t=>t.latitude).join(","),longitude:TRAIL_CATALOG.map(t=>t.longitude).join(","),hourly:"apparent_temperature,precipitation_probability,wind_speed_10m",daily:"sunset",timezone:"Asia/Beirut",start_date:date,end_date:date});
 const response=await fetch(`https://api.open-meteo.com/v1/forecast?${params}`,{signal:AbortSignal.timeout(8000)});if(!response.ok)throw new Error("Weather unavailable");const raw=await response.json() as unknown;const rows=Array.isArray(raw)?raw:[raw];const retrievedAt=new Date().toISOString();const weather:Record<string,WeatherInput>={};
 rows.forEach((row,i)=>{const r=row as {hourly?:{apparent_temperature?:number[];precipitation_probability?:number[];wind_speed_10m?:number[]};daily?:{sunset?:string[]}};const apparent=r.hourly?.apparent_temperature||[],rain=r.hourly?.precipitation_probability||[],wind=r.hourly?.wind_speed_10m||[],sunset=r.daily?.sunset?.[0];if(!apparent.length||!sunset)return;weather[TRAIL_CATALOG[i].id]={apparent:Math.max(...apparent.filter(Number.isFinite)),rain:Math.max(...rain.filter(Number.isFinite)),wind:Math.max(...wind.filter(Number.isFinite)),sunsetHour:+sunset.slice(11,13)+ +sunset.slice(14,16)/60,retrievedAt}});return weather;
}
function seededDemoWeather(){const retrievedAt="2026-07-25T04:00:00-04:00",values:Record<string,[number,number,number]>={"new-york-central-park-xtreme":[25,8,12],"roosevelt-island-manhattan":[29,18,22],barouk:[24,8,14],arsoun:[31,12,18],"jouar-el-haouz":[29,18,24],"cedars-lake":[27,10,30],"falougha-summit":[30,25,38],ehden:[28,20,26],baskinta:[32,30,35]};return Object.fromEntries(TRAIL_CATALOG.map(t=>{const [apparent,rain,wind]=values[t.id]||[28,15,22];return [t.id,{apparent,rain,wind,sunsetHour:20.35,retrievedAt} satisfies WeatherInput]}))}

export async function POST(request:Request){const value=await request.json().catch(()=>null);const input=validateRequest(value);if(!input)return Response.json({error:"Invalid daily recommendation request"},{status:400});let weather:Record<string,WeatherInput|undefined>={},partial=false;if(input.demo_mode)weather=seededDemoWeather();else try{weather=await getWeather(input.date)}catch{partial=true}const ranked=rankTrails(input,weather);saveRecommendations(ranked);return Response.json({recommendationId:`daily-${input.date}-${Date.now()}`,generatedAt:new Date().toISOString(),timezone:input.demo_mode?"America/New_York":"Asia/Beirut",dataSource:input.demo_mode?"seeded-demo":"open-meteo",partialData:partial,groups:ranked.filter(r=>r.group),ranked,excluded:ranked.filter(r=>!r.eligible)})}
