import { estimateBaselineHours, TRAIL_CATALOG, type Difficulty, type HikerProfile, type TrailCatalogEntry } from "./trail-catalog.ts";
export { TRAIL_CATALOG } from "./trail-catalog.ts";
export type DailyRequest = { date:string; preferred_departure_time:string; starting_location:{latitude:number;longitude:number}; maximum_drive_minutes:number; available_total_hours:number; preferred_difficulty:Difficulty[]; preferred_features:string[]; avoid_features:string[]; profile:HikerProfile; demo_mode?:boolean };
export type WeatherInput = { apparent:number; rain:number; wind:number; sunsetHour:number; retrievedAt:string };
export type Factor = { code:string;message:string;impact:number };
export type Recommendation = { recommendationId:string;trailId:string;name:string;country:string;group?:"Best Match"|"More Adventurous"|"Easier Alternative";eligible:boolean;exclusions:string[];overallScore:number;componentScores:{fitness:number;weather:number;daylight:number;preference:number;logistics:number;confidence:number};driveMinutes:number;hikeHours:number;finishTime:string;daylightBufferHours:number|null;weatherSummary:string;hardestSegment:string;positiveFactors:Factor[];negativeFactors:Factor[];concerns:string[];confidenceLevel:"high"|"medium"|"low";freshness:{weatherRetrievedAt:string|null;trailDataTimestamp:string;analysisVersion:string;scoringVersion:string} };

export const ANALYSIS_VERSION="2026.07"; export const SCORING_VERSION="daily-v1";
export const WEIGHTS={fitness:.30,weather:.20,daylight:.15,preference:.15,logistics:.10,confidence:.10} as const;
export interface DriveTimeProvider { estimateMinutes(from:{latitude:number;longitude:number},trail:TrailCatalogEntry):number }
export const distanceDriveProvider:DriveTimeProvider={estimateMinutes(from,trail){const R=6371,p1=from.latitude*Math.PI/180,p2=trail.latitude*Math.PI/180,dp=(trail.latitude-from.latitude)*Math.PI/180,dl=(trail.longitude-from.longitude)*Math.PI/180,q=Math.sin(dp/2)**2+Math.cos(p1)*Math.cos(p2)*Math.sin(dl/2)**2;const km=2*R*Math.atan2(Math.sqrt(q),Math.sqrt(1-q));return Math.round(km*1.35/45*60)}};
const clamp=(n:number)=>Math.max(0,Math.min(100,Math.round(n)));
const clock=(h:number)=>`${String(Math.floor((h+24)%24)).padStart(2,"0")}:${String(Math.round((h%1)*60)).padStart(2,"0")}`;
const level=(d:Difficulty)=>({easy:1,moderate:2,advanced:3})[d];

export function validateRequest(v:unknown):DailyRequest|null { if(!v||typeof v!=="object")return null;const r=v as Partial<DailyRequest>;if(!/^\d{4}-\d{2}-\d{2}$/.test(r.date||"")||!/^\d{2}:\d{2}$/.test(r.preferred_departure_time||"")||!r.starting_location||!r.profile)return null;if(!Number.isFinite(r.starting_location.latitude)||!Number.isFinite(r.starting_location.longitude)||!Number.isFinite(r.maximum_drive_minutes)||!Number.isFinite(r.available_total_hours)||!Array.isArray(r.preferred_difficulty)||!Array.isArray(r.preferred_features)||!Array.isArray(r.avoid_features))return null;return r as DailyRequest }

export function rankTrails(request:DailyRequest,weathers:Record<string,WeatherInput|undefined>,driveProvider:DriveTimeProvider=distanceDriveProvider){
 const dep=+request.preferred_departure_time.slice(0,2)+ +request.preferred_departure_time.slice(3)/60;
 const ranked:Recommendation[]=TRAIL_CATALOG.map(trail=>{const w=weathers[trail.id],drive=driveProvider.estimateMinutes(request.starting_location,trail),hike=estimateBaselineHours(trail,request.profile),finish=dep+hike,buffer=w?w.sunsetHour-finish:null;
  const exclusions:string[]=[];if(!trail.active)exclusions.push("TRAIL_UNAVAILABLE");if(drive>request.maximum_drive_minutes)exclusions.push("DRIVE_TIME_EXCEEDED");if(hike>request.available_total_hours)exclusions.push("HIKING_TIME_EXCEEDED");if(request.avoid_features.some(f=>trail.features.includes(f)))exclusions.push("EXCLUDED_FEATURE");if(trail.confidence<60)exclusions.push("INSUFFICIENT_CONFIDENCE");if(buffer!==null&&buffer<-.25)exclusions.push("INSUFFICIENT_DAYLIGHT");if(w&&(w.rain>=85||w.wind>=60))exclusions.push("SEVERE_WEATHER");
  const fitness=clamp(100-Math.max(0,trail.distanceKm/request.profile.distanceKm-1)*45-Math.max(0,trail.ascentM/request.profile.ascentM-1)*45-Math.abs(level(trail.difficulty)-Math.max(...request.preferred_difficulty.map(level),2))*12);
  const weather=clamp(w?100-Math.max(0,w.apparent-26)*5-w.rain*.45-Math.max(0,w.wind-20)*1.5:55),daylight=clamp(buffer===null?55:65+buffer*15);
  const preferred=request.preferred_features.length?request.preferred_features.filter(f=>trail.features.includes(f)).length/request.preferred_features.length:1;const preference=clamp(55+preferred*35-(request.preferred_difficulty.includes(trail.difficulty)?0:18));const logistics=clamp(100-drive/request.maximum_drive_minutes*55-hike/request.available_total_hours*25);const confidence=clamp(trail.confidence-(w?0:20));
  const components={fitness,weather,daylight,preference,logistics,confidence};const overall=clamp(Object.entries(WEIGHTS).reduce((s,[k,v])=>s+components[k as keyof typeof components]*v,0));const positiveFactors:Factor[]=[{code:"FITNESS_MATCH",message:`${trail.distanceKm} km and ${trail.ascentM} m ascent fit the selected profile.`,impact:+(fitness*WEIGHTS.fitness).toFixed(1)},{code:"DAYLIGHT_MARGIN",message:buffer===null?"Daylight forecast is unavailable.":`${buffer.toFixed(1)} hours of modeled daylight remain.`,impact:+(daylight*WEIGHTS.daylight).toFixed(1)}];const negativeFactors:Factor[]=[];if(w&&w.apparent>=30)negativeFactors.push({code:"AFTERNOON_HEAT",message:`Apparent temperature may reach ${Math.round(w.apparent)}°C.`,impact:-Math.round((100-weather)*WEIGHTS.weather)});if(!w)negativeFactors.push({code:"MISSING_WEATHER",message:"Live hourly weather is unavailable; suitability is conservative.",impact:-9});
  return {recommendationId:`${request.date}-${trail.id}`,trailId:trail.id,name:trail.name,country:trail.country||"Lebanon",eligible:exclusions.length===0,exclusions,overallScore:overall,componentScores:components,driveMinutes:drive,hikeHours:+hike.toFixed(2),finishTime:clock(finish),daylightBufferHours:buffer===null?null:+buffer.toFixed(2),weatherSummary:w?`${Math.round(w.apparent)}°C feels-like · ${Math.round(w.rain)}% rain · ${Math.round(w.wind)} km/h wind`:"Hourly weather unavailable",hardestSegment:`Highest modeled climbing load near the final third (${trail.ascentM} m total ascent).`,positiveFactors,negativeFactors,concerns:[...exclusions,...negativeFactors.map(f=>f.message)],confidenceLevel:(confidence>=85?"high":confidence>=65?"medium":"low") as "high"|"medium"|"low",freshness:{weatherRetrievedAt:w?.retrievedAt||null,trailDataTimestamp:trail.updatedAt,analysisVersion:ANALYSIS_VERSION,scoringVersion:SCORING_VERSION}} satisfies Recommendation}).sort((a,b)=>Number(b.eligible)-Number(a.eligible)||b.overallScore-a.overallScore||a.trailId.localeCompare(b.trailId));
 const eligible=ranked.filter(r=>r.eligible);if(eligible[0])eligible[0].group="Best Match";const bestTrail=eligible[0]&&TRAIL_CATALOG.find(t=>t.id===eligible[0].trailId);const bestLoad=bestTrail?bestTrail.distanceKm+bestTrail.ascentM/100:0;const adventurous=eligible.find(r=>{if(r===eligible[0])return false;const t=TRAIL_CATALOG.find(x=>x.id===r.trailId)!;return level(t.difficulty)>level(bestTrail?.difficulty||"moderate")||t.distanceKm+t.ascentM/100>bestLoad*1.05});if(adventurous)adventurous.group="More Adventurous";const easier=eligible.find(r=>{if(r===eligible[0]||r===adventurous)return false;const t=TRAIL_CATALOG.find(x=>x.id===r.trailId)!;return level(t.difficulty)<level(bestTrail?.difficulty||"moderate")||t.distanceKm+t.ascentM/100<bestLoad*.85});if(easier)easier.group="Easier Alternative";return ranked;
}
