import { createHash } from "node:crypto";

export type TrailImportMetadata={file:string;id:string;name:string;detail:string;region:string;country:string;activity_type:"hiking";source_type:"user_provided";source_platform:string|null;source_url:string|null;source_author:string|null;contribution_date:string;permission_to_use:boolean;public_download_allowed:boolean;visibility:"public"|"demo-only";description:string;tags:string[]};
export type ParsedPoint={lat:number;lon:number;ele:number;distance:number};
export type ImportedTrail={id:string;file:string;name:string;detail:string;region:string;country:string;latitude:number;longitude:number;distanceKm:number;ascentM:number;highPointM:number;difficulty:"easy"|"moderate"|"advanced";features:string[];exposure:"low"|"medium"|"high";confidence:number;updatedAt:string;active:boolean;provenance:{sourceType:string;sourcePlatform:string|null;sourceUrl:string|null;sourceAuthor:string|null;contributionDate:string;permissionToUse:boolean;publicDownloadAllowed:boolean;visibility:string;gpxChecksum:string;ingestedAt:string;analyticsVersion:string}};
export function curatedTrailId(file:string){const slug=file.replace(/\.gpx$/i,"").toLowerCase().normalize("NFKD").replace(/[^a-z0-9]+/g,"-").replace(/^-|-$/g,"");return `curated-${slug||"trail"}`}
export function curatedTrailName(file:string){return file.replace(/\.gpx$/i,"").split(/[-_]+/).filter(Boolean).map(word=>word.charAt(0).toUpperCase()+word.slice(1)).join(" ")}
export function createCuratedMetadata(file:string):TrailImportMetadata{return {file,id:curatedTrailId(file),name:curatedTrailName(file),detail:"Curated Lebanon hiking route",region:"Lebanon",country:"Lebanon",activity_type:"hiking",source_type:"user_provided",source_platform:null,source_url:null,source_author:null,contribution_date:"owner-curated",permission_to_use:true,public_download_allowed:false,visibility:"public",description:"Project-owner curated trail imported automatically for the public demo.",tags:[]}}
export function discoverCuratedMetadata(files:string[],configured:TrailImportMetadata[]){const byFile=new Map(configured.map(item=>[item.file.toLowerCase(),item]));return [...files].sort((a,b)=>a.localeCompare(b)).map(file=>byFile.get(file.toLowerCase())||createCuratedMetadata(file))}
const R=6371000;
export function haversine(a:ParsedPoint,b:ParsedPoint){const p1=a.lat*Math.PI/180,p2=b.lat*Math.PI/180,dp=(b.lat-a.lat)*Math.PI/180,dl=(b.lon-a.lon)*Math.PI/180,q=Math.sin(dp/2)**2+Math.cos(p1)*Math.cos(p2)*Math.sin(dl/2)**2;return 2*R*Math.atan2(Math.sqrt(q),Math.sqrt(1-q))}
export function validateMetadata(value:unknown):string[]{const m=value as Partial<TrailImportMetadata>,errors:string[]=[];for(const key of ["file","id","name","region","country","activity_type","source_type","contribution_date","visibility"] as const)if(!m?.[key])errors.push(`missing ${key}`);if(m.activity_type!=="hiking")errors.push("activity_type must be hiking");if(m.permission_to_use!==true)errors.push("permission_to_use must be true");if(!Array.isArray(m.tags))errors.push("tags must be an array");return errors}
export function parseGpx(xml:string):ParsedPoint[]{const points:ParsedPoint[]=[];const re=/<(?:trkpt|rtept)\b[^>]*\blat=["']([^"']+)["'][^>]*\blon=["']([^"']+)["'][^>]*>([\s\S]*?)<\/(?:trkpt|rtept)>/gi;let match:RegExpExecArray|null,distance=0;while((match=re.exec(xml))){const lat=Number(match[1]),lon=Number(match[2]),ele=Number(match[3].match(/<ele>([^<]+)<\/ele>/i)?.[1]||0);if(!Number.isFinite(lat)||!Number.isFinite(lon)||!Number.isFinite(ele))continue;const point={lat,lon,ele,distance};if(points.length){distance+=haversine(points.at(-1)!,point);point.distance=distance}points.push(point)}if(points.length<2)throw new Error("GPX must contain at least two valid track points");return points}
export function analyze(points:ParsedPoint[]){let ascent=0;for(let i=1;i<points.length;i++){const gain=points[i].ele-points[i-1].ele;if(gain>1)ascent+=gain}const distanceKm=points.at(-1)!.distance/1000,highPointM=Math.max(...points.map(p=>p.ele)),difficulty=distanceKm<=7&&ascent<=400?"easy":distanceKm<=16&&ascent<=900?"moderate":"advanced";return {distanceKm:+distanceKm.toFixed(1),ascentM:Math.round(ascent),highPointM:Math.round(highPointM),difficulty} as const}
export function checksum(text:string){return createHash("sha256").update(text).digest("hex")}
export function geometrySignature(points:ParsedPoint[]){const sample=[points[0],points[Math.floor(points.length/2)],points.at(-1)!];return sample.map(p=>`${p.lat.toFixed(4)},${p.lon.toFixed(4)}`).join("|")}
export function decimate(points:ParsedPoint[],limit=600){if(points.length<=limit)return points;const result:ParsedPoint[]=[];for(let i=0;i<limit;i++)result.push(points[Math.round(i*(points.length-1)/(limit-1))]);return result}
